name: TenisMonster actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build the game
    runs-on: ubuntu-latest
    steps:
      # Checkout the rpository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Use cache for quicker build times
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build the game
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }} # must be set in the github repository
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }} # must be set in the github repository
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }} # must be set in the github repository
        with:
          targetPlatform: StandaloneWindows64
          allowDirtyBuild: true